server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://{HOST}:3306/{DATABASE_NAME}
    username: {DATABASE_USERNAME}
    password: {DATABASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: {HOST}
      port: 6379
      timeout: 8000ms